### ISSUE TITLE
import "cowsay"

### ISSUE THREAD

**Issue by Jonathan357611** [Anomic-cr/i3_dotfiles#1]
Hey, Awesome design you got there!
In your install script you try to run "cowsay.daemon('welcome' + now)" while it is not imported.
Fix this with adding ```import cowsay``` to the imports.

also, not everyone has cowsay installed, so you might want to reference this in your README.md or create a [requirements.txt](https://pip.pypa.io/en/latest/reference/requirements-file-format/) where you add this requirement :)

Keep the good work up!

**Comment by Anomic-cr** [comment]
thanks for point that out I'll add that import and will update the readme
